name: "Actual Budget Sync"
description: "Sync categories and transactions between Budgets"
startup: "application"
version: "1.0.12"
slug: "actual_budget_sync"
init: false
arch:
  - aarch64
image: "ghcr.io/mikeomat/ha-actual-budget-sync"
map:
 - type: addon_config
   path: /config


